apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flaskapps.crd.domain
spec:
  group: crd.domain
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                replicas:
                  type: integer
                image:
                  type: string
                serviceType:
                  type: string
                serviceAccountName:
                  type: string
                configMapName:            
                  type: string
                configData:               
                  type: object
                  additionalProperties:   # ConfigMap verisi, key-value formatında olacak
                    type: string
                
                
                pvcName:
                  type: string
                storageClassName:
                  type: string
                storageSize:
                  type: string
                accessModes:
                  type: array
                  items:
                    type: string
                pvPath:
                  type: string

                
          

  scope: Namespaced
  names:
    plural: flaskapps
    singular: flaskapp
    kind: FlaskApp
    shortNames:
    - fa
